In [131]:
using Pkg
Pkg.status()

      Status `~/datalake/lab/Crypto/Project.toml`
  [336ed68f] CSV v0.8.5
  [a93c6f00] DataFrames v1.2.2
  [f7bf1975] Impute v0.6.6
  [e1d29d7a] Missings v1.0.1

In [8]:
using CSV
using DataFrames
using Impute
using Missings
using ScikitLearn

# From CSV to Dataframe

In [16]:
eltype.(eachcol(CSV.File("/home/giujorge/datalake/stock/crypto/yahoo/daily/BTC/BTC-USD.csv") |> DataFrame ))

7-element Vector{DataType}:
 Dates.Date
 String
 String
 String
 String
 String
 String

In [171]:
df  = CSV.read("/home/giujorge/datalake/stock/crypto/yahoo/daily/BTC/BTC-USD.csv", DataFrame; missingstring = "null", types=Dict(:Open => Float64,:Low => Float64, :Close => Float64, :Volume => Int64))

2544×7 DataFrame
  Row │ Date        Open       High       Low        Close      Adj Close  Vol ⋯
      │ Date…       Float64?   Float64?   Float64?   Float64?   Float64?   Int ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │ 2014-09-17    465.864    468.174    452.422    457.334    457.334      ⋯
    2 │ 2014-09-18    456.86     456.86     413.104    424.44     424.44
    3 │ 2014-09-19    424.103    427.835    384.532    394.796    394.796
    4 │ 2014-09-20    394.673    423.296    389.883    408.904    408.904
    5 │ 2014-09-21    408.085    412.426    393.181    398.821    398.821      ⋯
    6 │ 2014-09-22    399.1      406.916    397.13     402.152    402.152
    7 │ 2014-09-23    402.092    441.557    396.197    435.791    435.791
    8 │ 2014-09-24    435.751    436.112    421.132    423.205    423.205
    9 │ 2014-09-25    423.156    423.52     409.468    411.574    411.574      ⋯
   10 │ 2014-09-26    411.429    414.938    400.009    404.425    404.425
   11 │ 2014-09-27    403.556    406.623    397.372    399.52     399.52
  ⋮   │     ⋮           ⋮          ⋮          ⋮          ⋮          ⋮          ⋱
 2535 │ 2021-08-25  47727.3    49202.9    47163.6    48960.8    48960.8    326
 2536 │ 2021-08-26  49002.6    49347.6    46405.8    46942.2    46942.2    326 ⋯
 2537 │ 2021-08-27  46894.6    49112.8    46394.3    49058.7    49058.7    345
 2538 │ 2021-08-28  49072.6    49283.5    48499.2    48902.4    48902.4    285
 2539 │ 2021-08-29  48911.2    49644.1    47925.9    48829.8    48829.8    258
 2540 │ 2021-08-30  48834.9    48925.6    46950.3    47055.0    47055.0    318 ⋯
 2541 │ 2021-08-31  47024.3    48189.6    46750.1    47166.7    47166.7    347
 2542 │ 2021-09-01  47099.8    49111.1    46562.4    48847.0    48847.0    391
 2543 │ 2021-09-02  48807.8    50343.4    48652.3    49327.7    49327.7    395
 2544 │ 2021-09-03  49341.1    50956.6    48458.0    50179.9    50179.9    432 ⋯
                                                  1 column and 2523 rows omitted

In [172]:
rename!(df,:"Adj Close" => :Adj_Close)

2544×7 DataFrame
  Row │ Date        Open       High       Low        Close      Adj_Close  Vol ⋯
      │ Date…       Float64?   Float64?   Float64?   Float64?   Float64?   Int ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │ 2014-09-17    465.864    468.174    452.422    457.334    457.334      ⋯
    2 │ 2014-09-18    456.86     456.86     413.104    424.44     424.44
    3 │ 2014-09-19    424.103    427.835    384.532    394.796    394.796
    4 │ 2014-09-20    394.673    423.296    389.883    408.904    408.904
    5 │ 2014-09-21    408.085    412.426    393.181    398.821    398.821      ⋯
    6 │ 2014-09-22    399.1      406.916    397.13     402.152    402.152
    7 │ 2014-09-23    402.092    441.557    396.197    435.791    435.791
    8 │ 2014-09-24    435.751    436.112    421.132    423.205    423.205
    9 │ 2014-09-25    423.156    423.52     409.468    411.574    411.574      ⋯
   10 │ 2014-09-26    411.429    414.938    400.009    404.425    404.425
   11 │ 2014-09-27    403.556    406.623    397.372    399.52     399.52
  ⋮   │     ⋮           ⋮          ⋮          ⋮          ⋮          ⋮          ⋱
 2535 │ 2021-08-25  47727.3    49202.9    47163.6    48960.8    48960.8    326
 2536 │ 2021-08-26  49002.6    49347.6    46405.8    46942.2    46942.2    326 ⋯
 2537 │ 2021-08-27  46894.6    49112.8    46394.3    49058.7    49058.7    345
 2538 │ 2021-08-28  49072.6    49283.5    48499.2    48902.4    48902.4    285
 2539 │ 2021-08-29  48911.2    49644.1    47925.9    48829.8    48829.8    258
 2540 │ 2021-08-30  48834.9    48925.6    46950.3    47055.0    47055.0    318 ⋯
 2541 │ 2021-08-31  47024.3    48189.6    46750.1    47166.7    47166.7    347
 2542 │ 2021-09-01  47099.8    49111.1    46562.4    48847.0    48847.0    391
 2543 │ 2021-09-02  48807.8    50343.4    48652.3    49327.7    49327.7    395
 2544 │ 2021-09-03  49341.1    50956.6    48458.0    50179.9    50179.9    432 ⋯
                                                  1 column and 2523 rows omitted

In [153]:
first(df, 10)

10×7 DataFrame
 Row │ Date        Open      High      Low       Close     Adj_Close  Volume   ⋯
     │ Date…       Float64?  Float64?  Float64?  Float64?  Float64?   Int64?   ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 2014-09-17   465.864   468.174   452.422   457.334    457.334  21056800 ⋯
   2 │ 2014-09-18   456.86    456.86    413.104   424.44     424.44   34483200
   3 │ 2014-09-19   424.103   427.835   384.532   394.796    394.796  37919700
   4 │ 2014-09-20   394.673   423.296   389.883   408.904    408.904  36863600
   5 │ 2014-09-21   408.085   412.426   393.181   398.821    398.821  26580100 ⋯
   6 │ 2014-09-22   399.1     406.916   397.13    402.152    402.152  24127600
   7 │ 2014-09-23   402.092   441.557   396.197   435.791    435.791  45099500
   8 │ 2014-09-24   435.751   436.112   421.132   423.205    423.205  30627700
   9 │ 2014-09-25   423.156   423.52    409.468   411.574    411.574  26814400 ⋯
  10 │ 2014-09-26   411.429   414.938   400.009   404.425    404.425  21460800

In [154]:
last(df, 10)

10×7 DataFrame
 Row │ Date        Open      High      Low       Close     Adj_Close  Volume   ⋯
     │ Date…       Float64?  Float64?  Float64?  Float64?  Float64?   Int64?   ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 2021-08-25   47727.3   49202.9   47163.6   48960.8    48960.8  32646349 ⋯
   2 │ 2021-08-26   49002.6   49347.6   46405.8   46942.2    46942.2  32666549
   3 │ 2021-08-27   46894.6   49112.8   46394.3   49058.7    49058.7  34511076
   4 │ 2021-08-28   49072.6   49283.5   48499.2   48902.4    48902.4  28568103
   5 │ 2021-08-29   48911.2   49644.1   47925.9   48829.8    48829.8  25889650 ⋯
   6 │ 2021-08-30   48834.9   48925.6   46950.3   47055.0    47055.0  31847007
   7 │ 2021-08-31   47024.3   48189.6   46750.1   47166.7    47166.7  34730363
   8 │ 2021-09-01   47099.8   49111.1   46562.4   48847.0    48847.0  39139399
   9 │ 2021-09-02   48807.8   50343.4   48652.3   49327.7    49327.7  39508070 ⋯
  10 │ 2021-09-03   49341.1   50956.6   48458.0   50179.9    50179.9  43296890
                                                                1 column omitted

# Descriptive

In [155]:
println(size(df))

(2544, 7)

In [156]:
println(summary(df))

2544×7 DataFrame

In [157]:
names(df)

7-element Vector{String}:
 "Date"
 "Open"
 "High"
 "Low"
 "Close"
 "Adj_Close"
 "Volume"

In [169]:
describe(df)

7×7 DataFrame
 Row │ variable   mean        min         median     max           nmissing  e ⋯
     │ Symbol     Union…      Any         Union…     Any           Int64     T ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ Date                   2014-09-17             2021-09-03           0  D ⋯
   2 │ Open       8739.89     176.897     5218.71    63523.8              0  U
   3 │ High       8989.63     211.731     5329.03    64863.1              0  U
   4 │ Low        8470.52     171.51      5065.46    62209.0              0  U
   5 │ Close      8758.7      178.103     5230.59    63503.5              0  U ⋯
   6 │ Adj_Close  8758.7      178.103     5230.59    63503.5              0  U
   7 │ Volume     1.33566e10  5914570     4.34272e9  350967941479         0  U
                                                                1 column omitted

# Missing Values

In [173]:
df[ismissing.(df.Open), :]

4×7 DataFrame
 Row │ Date        Open      High      Low       Close     Adj_Close  Volume
     │ Date…       Float64?  Float64?  Float64?  Float64?  Float64?   Int64?
─────┼────────────────────────────────────────────────────────────────────────
   1 │ 2020-04-17   missing   missing   missing   missing    missing  missing
   2 │ 2020-10-09   missing   missing   missing   missing    missing  missing
   3 │ 2020-10-12   missing   missing   missing   missing    missing  missing
   4 │ 2020-10-13   missing   missing   missing   missing    missing  missing

In [179]:
df = Impute.locf(df)

2544×7 DataFrame
  Row │ Date        Open       High       Low        Close      Adj_Close  Vol ⋯
      │ Date…       Float64?   Float64?   Float64?   Float64?   Float64?   Int ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │ 2014-09-17    465.864    468.174    452.422    457.334    457.334      ⋯
    2 │ 2014-09-18    456.86     456.86     413.104    424.44     424.44
    3 │ 2014-09-19    424.103    427.835    384.532    394.796    394.796
    4 │ 2014-09-20    394.673    423.296    389.883    408.904    408.904
    5 │ 2014-09-21    408.085    412.426    393.181    398.821    398.821      ⋯
    6 │ 2014-09-22    399.1      406.916    397.13     402.152    402.152
    7 │ 2014-09-23    402.092    441.557    396.197    435.791    435.791
    8 │ 2014-09-24    435.751    436.112    421.132    423.205    423.205
    9 │ 2014-09-25    423.156    423.52     409.468    411.574    411.574      ⋯
   10 │ 2014-09-26    411.429    414.938    400.009    404.425    404.425
   11 │ 2014-09-27    403.556    406.623    397.372    399.52     399.52
  ⋮   │     ⋮           ⋮          ⋮          ⋮          ⋮          ⋮          ⋱
 2535 │ 2021-08-25  47727.3    49202.9    47163.6    48960.8    48960.8    326
 2536 │ 2021-08-26  49002.6    49347.6    46405.8    46942.2    46942.2    326 ⋯
 2537 │ 2021-08-27  46894.6    49112.8    46394.3    49058.7    49058.7    345
 2538 │ 2021-08-28  49072.6    49283.5    48499.2    48902.4    48902.4    285
 2539 │ 2021-08-29  48911.2    49644.1    47925.9    48829.8    48829.8    258
 2540 │ 2021-08-30  48834.9    48925.6    46950.3    47055.0    47055.0    318 ⋯
 2541 │ 2021-08-31  47024.3    48189.6    46750.1    47166.7    47166.7    347
 2542 │ 2021-09-01  47099.8    49111.1    46562.4    48847.0    48847.0    391
 2543 │ 2021-09-02  48807.8    50343.4    48652.3    49327.7    49327.7    395
 2544 │ 2021-09-03  49341.1    50956.6    48458.0    50179.9    50179.9    432 ⋯
                                                  1 column and 2523 rows omitted

# Imputer selection